config/routes.rb
Rails.application.routes.draw do

  devise_for :landlords, controllers: {
        sessions: 'landlords/sessions', 
        registrations: 'landlords/registrations',
        passwords: 'landlords/passwords'
      }
  

  get '/properties/apply' => 'properties#apply', as: 'properties_apply'
  post '/properties/apply' => 'properties#application_request'
  get '/landlords/contact' => 'landlords#contact', as: 'landlords_contact'
  post 'tennants/sign_in' => 'sessions#create', as: 'sessions_create'
  get '/sessions/sign_in' => 'sessions#new', as: 'sessions'
  delete '/sessions/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/tennants/maintanence' => 'tennants#maintanence', as: 'tennants_maintanence'
  post '/tennants/maintanence' => 'tennants#maintanence_request'
  get '/tennants/:id/pay' => 'tennants#pay', as: 'tennants_pay'
  get '/properties/all' => 'properties#all', as: 'properties_all'
  get '/properties/:id/liststatus' => 'properties#liststatus', as: 'properties_liststatus'

  resources :tennants  
  resources :properties 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


root to: "home#index"
end

app/models/property.rb
class Property < ApplicationRecord

	has_one :tennant

	has_many :images

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
	default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	scope :listed, -> { where(listed: true) }
	
	def statusChange
		self.listed = !self.listed
		save
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	
	before_action :authenticate_landlord!, only: [:all, :liststatus, :new, :create, :edit, :destroy, :update ]

	def index
		@properties = Property.listed
	end 

	def all
		@properties = Property.all
	end

	def liststatus
		@property = Property.find(params[:id]).statusChange
		redirect_to properties_all_path
	end 

	def new
		@property = Property.new
	end

	def apply
    end

	def show

  	end

	def create
	    @property = Property.new(property_params)
	    if @property.save
	        redirect_to properties_all_path 
	    else
	      render "new"
	    end
	end
	# pony gem used to send an email with a rental application to a protential potential tennant 
	def application_request
		Pony.mail(to: params[:email], from: "bradwflint@gmail.com", subject: "Email application", body: "Here is the rental application!", :attachments => {"rentalapp.pdf" => File.read(Rails.root.to_s + "/public/rentalapp.pdf")} )
	    # Pony.mail(to: "bradwflint@gmail.com", from: "bradwflint@gmail.com", subject: "Email application", body: "Here is the rental application!", :attachments => {"rentalapp.pdf" => File.read(Rails.root.to_s + "/public/rentalapp.pdf")} )
		redirect_to properties_apply_path
	end

   def apply
		
   end

   def edit
   	@property = Property.find(params[:id])
   end

   def destroy
	    Property.find(params[:id]).destroy
	    redirect_to properties_all_path
	end

	def update
	    @property = Property.find(params[:id])
	       if @property.update_attributes(property_params)
              redirect_to properties_path
	       else
		       render 'edit'
		   end
	end

    private
	def property_params
	    params.require(:property).permit(:property_id, :address, :city, :state, :zip, :monthly_rent, :date_available, :bedrooms, :bathrooms, :square_feet, :description, :pet_policy, :security_deposit, :application_fee, :avatar)
	end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_edit.html.erb
<!-- displays the header and "Edit Property" inside the box  -->
<div align= center id="edit_property">
	<div align=center id="properties_edit">
		<h1>EDIT PROPERTY</h1>
	</div>
	<hr>
<!-- form the landlord uses to edit a property -->
	<%= form_for @property, :html => {:multipart => true} do |f| %>

	   <div class="field">
	     <%= f.label :address, "Street Address" %>
	     <%= f.text_field :address, autofocus: true %>
	   </div>

	   <div class="field">
	     <%= f.label :city, "City" %>
	     <%= f.text_field :city %>
	   </div>

	   <div class="field">
	     <%= f.label :state, "State" %>
	     <%= f.text_field :state %>
	   </div>

	   <div class="field">
	     <%= f.label :zip, "Zip Code" %>
	     <%= f.text_field :zip %>
	   </div>

	   <div class="field">
	     <%= f.label :monthly_rent, "Monthly Rent" %>
	     <%= f.text_field :monthly_rent %>
	   </div>

	   <div class="field">
	     <%= f.label :bedrooms, "Bedrooms" %>
	     <%= f.text_field :bedrooms %>
	   </div>

	   <div class="field">
	     <%= f.label :bathrooms, "Bathrooms" %>
	     <%= f.text_field :bathrooms %>
	   </div>

	   <div class="field">
	     <%= f.label :square_feet, "Sq Feet" %>
	     <%= f.text_field :square_feet %>
	   </div>

	   <div class="field">
	     <%= f.label :description, "Desciption" %>
	     <%= f.text_field :description  %>
	   </div>

	   <div class="field">
	     <%= f.label :pet_policy, "Pet Policy" %>
	     <%= f.text_field :pet_policy %>
	   </div>

	   <div class="field">
	     <%= f.label :security_deposit, "Security Deposit" %>
	     <%= f.text_field :security_deposit %>
	   </div>

	   <div class="field">
	     <%= f.label :application_fee, "Application Fee" %>
	     <%= f.text_field :application_fee %>
	   </div>

	    <div class="field">
	     <%= f.label :date_available, "Date Available", class: "select" %>
	     <%= f.date_select :date_available %>
	   </div>

	   <%= f.file_field :avatar %>
	   
	  <div class="actions">
	    <%= f.submit(:class => "btn_box") %>
	  </div>

	 <% end %>
</div>

app/views/properties/_new.html.erb
<!-- displays header and "Create New Property" text inside the box-->
<div align= center id="create_new_property">
	<div align=center id="properties_new">
		<h1>CREATE NEW PROPERTY</h1>
	</div>
	<hr>
	<br>
	<%= form_for @property, :url => properties_path, :html => { :multipart => true } do |f| %>
<!-- form the landlord uses to create a new property -->
	   <div class="field">
	     <%= f.label :address, "Street Address" %>
	     <%= f.text_field :address, autofocus: true %>
	   </div>

	    <div class="field">
	     <%= f.label :city, "City" %>
	     <%= f.text_field :city %>
	   </div>

	    <div class="field">
	     <%= f.label :state, "State" %>
	     <%= f.text_field :state %>
	   </div>

	    <div class="field">
	     <%= f.label :zip, "Zip Code" %>
	     <%= f.text_field :zip %>
	   </div>

	    <div class="field">
	     <%= f.label :monthly_rent, "Monthly Rent" %>
	     <%= f.text_field :monthly_rent %>
	   </div>

	    <div class="field">
	     <%= f.label :bedrooms, "Bedrooms" %>
	     <%= f.text_field :bedrooms %>
	   </div>

	    <div class="field">
	     <%= f.label :bathrooms, "Bathrooms" %>
	     <%= f.text_field :bathrooms %>
	   </div>

	    <div class="field">
	     <%= f.label :square_feet, "Sq Feet" %>
	     <%= f.text_field :square_feet %>
	   </div>

	    <div class="field">
	     <%= f.label :description, "Desciption" %>
	     <%= f.text_field :description  %>
	   </div>

	    <div class="field">
	     <%= f.label :pet_policy, "Pet Policy" %>
	     <%= f.text_field :pet_policy %>
	   </div>

	    <div class="field">
	     <%= f.label :security_deposit, "Security Deposit" %>
	     <%= f.text_field :security_deposit %>
	   </div>

	    <div class="field">
	     <%= f.label :application_fee, "Application Fee" %>
	     <%= f.text_field :application_fee %>
	   </div>

	   <div class="field">
	     <%= f.label :date_available, "Date Available" %>
	     <%= f.date_field :date_available %>
	   </div>
<!-- allows the use of a photo -->
	 	<%= f.file_field :avatar, type: :file %>
	 
	   <div class="actions">
	    <%= f.submit nil, :class => 'btn_box' %>
	  </div>

	<% end %>
</div>

app/views/properties/_property.html.erb
<!-- the class is hidden if the home is not clicked on to be displayed on the page -->
<div class="property <%= hidden_class if hidden_class %>" data-id="<%= property.id%>">
	 <!-- displays the image and property information -->
		<div class="property_image">
			<%= image_tag property.avatar.url %><br>
		</div>
		<br>
		<div align =center id="property_address1">
			<%= property.address%>
			<%= property.city%>,
			<%= property.state%>
			<%= property.zip%><br>
		</div>
		Bedrooms: <%= property.bedrooms%><br>
		Bathrooms: <%= property.bathrooms%><br>
		Sq feet: <%= property.square_feet%><br>
		Pet Policy: <%= property.pet_policy%><br>
		Monlthly Rent: $<%= property.monthly_rent%><br>
		Security Deposit: $<%= property.security_deposit%><br>
		Application Fee: $<%= property.application_fee%><br>
		Available Date: <%= property.date_available.strftime("%m/%d/%y")%><br>
		<%= property.description%><br>
		<%= link_to "Click to Apply", properties_apply_path, :class => "apply_btn" %>
</div>
	

app/views/properties/all.html.erb
<!-- displays the header and "All Properties" text inside the box -->
<div align= center id="all_properties">
	<div align=center id="properties_label">
		<h1>ALL PROPERTIES</h1>
	</div>
	<hr>
	<br>
	<!-- loops through and displays all of the properties with image, info and links to Add Tennant, Delete Tennant, list or unlist property-->
	<% @properties.each do |property| %>
		<%= image_tag property.avatar.url(:thumb) %><br>
		<%= property.address%>
		<%= property.city%>
		<%= property.state%>
		<%= property.zip%>
		Rent $<%= property.monthly_rent%>
		Beds <%= property.bedrooms%>
		Baths <%= property.bathrooms%><br>
		<%= link_to "Add Tennant to Property", new_tennant_path(:tennant => {:property_id =>property.id}), :class => "property_btn" %> |
		<%= link_to "Edit Property", edit_property_path(property), :class => "property_btn" %> |
		<%= link_to "Delete Property", property_path(property), method: :delete, :class => "property_btn"  %> |
		<% if property.listed %>
		<!-- if property is listed, the Unlist Property will display, if the property is not listed, the List Property button will display  -->
		<%= link_to "Unlist Property", properties_liststatus_path(property), :class => "property_btn" %> 
		<% else %>
		<%= link_to "List Property", properties_liststatus_path(property), :class => "property_btn" %>
		<% end %> 
		<hr>
		<br>
	<%end%>
	
</div>

app/views/properties/apply.html.erb
<!-- displays the box header and "Application" text -->
<div id="application_form">
  <div id="application_label">
    <div id="apply">
      <h1>APPLICATION</h1>
    </div>
    <hr>
      <div id="apply_text">
        <p>Please be prepared to pay the application fee as outlined in the property listing. In addition to this rental application, you will also be required to provide a copy of a valid form of identification and proof of income.<br><br>

        To complete this rental application, you must be prepared to provide 3 years of residential history as well as contact information for your rental references. You will also be asked to provide information on your monthly income, and please note that most properties require that applicant combined gross income is at least three (3) times the monthly rent amount.<br>

        Each resident over the age of 18 must submit a separate rental application.</p>

        Applicant(s) understands that application fees are non-refundable . Security Deposits are Refundable within 48 hours of application, otherwise they are forfeitable. Applicant(s) that are not accepted will receive a Security Deposit refund.<br>
        Application fee: $40.00
        <h3>Enter your name and email address to have the application form emailed you.</h3>
      </div>
      <!-- form potential tennants can fill out to have the application emailed them -->
    	<%= form_tag properties_apply_path do %>
      <div id="apply_form">
        <%= label_tag :name, "Name" %>
        <%= text_field_tag :name %>
        <%= label_tag :email, "Email" %>
        <%= text_field_tag :email %>
        <%= submit_tag "Send", :class => "btn_box" %>
      </div>

      <% end %>
    </div>
</div>

app/views/properties/edit.html.erb
<%= render "properties/edit" %>

app/views/properties/index.html.erb
<div align = center id="homes_for_rent">
	<div align=center id="rent">
		<h1>HOMES FOR RENT</h1>
	</div>
	<hr>
	<br>
		<div id="homes">
			<% @properties.each do |property| %>
				<div class="home" data-id="<%= property.id%>">
					<%= image_tag property.avatar.url(:thumb) %><br>
					<%= property.address%>
					<%= property.city%>,
					<%= property.state%>
					<%= property.zip%><br>
					Rent $<%= property.monthly_rent%>
					Beds <%= property.bedrooms%>
					Baths <%= property.bathrooms%><br>
					<br>
				</div>
				<hr>
			<%end%>
		</div>

</div>

<div id="home_preview">
	<% @properties.each_with_index do |property, i| %>
		<%= render "property", property: property, hidden_class: (i != 0 ? 'hidden' : nil) %>
	<%end%>
</div>

app/views/properties/new.html.erb
<%= render "properties/new" %>