config/routes.rb
Rails.application.routes.draw do

  devise_for :landlords, controllers: {
        sessions: 'landlords/sessions', 
        registrations: 'landlords/registrations',
        passwords: 'landlords/passwords'
      }
  

  get '/properties/apply' => 'properties#apply', as: 'properties_apply'
  post '/properties/apply' => 'properties#application_request'
  get '/landlords/contact' => 'landlords#contact', as: 'landlords_contact'
  post 'tennants/sign_in' => 'sessions#create', as: 'sessions_create'
  get '/sessions/sign_in' => 'sessions#new', as: 'sessions'
  delete '/sessions/sign_out' => 'sessions#destroy', as: 'sign_out'
  get '/tennants/maintanence' => 'tennants#maintanence', as: 'tennants_maintanence'
  post '/tennants/maintanence' => 'tennants#maintanence_request'
  get '/tennants/:id/pay' => 'tennants#pay', as: 'tennants_pay'
  get '/properties/all' => 'properties#all', as: 'properties_all'
  get '/properties/:id/liststatus' => 'properties#liststatus', as: 'properties_liststatus'

  resources :tennants  
  resources :properties 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :property
	# paperclip gem used to allow the landlord to imput property images
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, 
	default_url: "/images/:style/missing.png"
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

	do_not_validate_attachment_file_type :image
end

app/models/landlord.rb
class Landlord < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/property.rb
class Property < ApplicationRecord

	has_one :tennant

	has_many :images

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, 
	default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	scope :listed, -> { where(listed: true) }
	
	def statusChange
		self.listed = !self.listed
		save
	end
end

app/models/tennant.rb
class Tennant < ApplicationRecord
	belongs_to :property
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	properties_all_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@property = Property.new
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

end

app/controllers/landlords/unlocks_controller.rb
class Landlords::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
   
   def contact
   end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	
	before_action :authenticate_landlord!, only: [:all, :liststatus, :new, :create, :edit, :destroy, :update ]

	def index
		@properties = Property.listed
	end 

	def all
		@properties = Property.all
	end

	def liststatus
		@property = Property.find(params[:id]).statusChange
		redirect_to properties_all_path
	end 

	def new
		@property = Property.new
	end

	def apply
    end

	def show

  	end

	def create
	    @property = Property.new(property_params)
	    if @property.save
	        redirect_to properties_all_path 
	    else
	      render "new"
	    end
	end
	# pony gem used to send an email with a rental application to a protential potential tennant 
	def application_request
		Pony.mail(to: params[:email], from: "bradwflint@gmail.com", subject: "Email application", body: "Here is the rental application!", :attachments => {"rentalapp.pdf" => File.read(Rails.root.to_s + "/public/rentalapp.pdf")} )
	    # Pony.mail(to: "bradwflint@gmail.com", from: "bradwflint@gmail.com", subject: "Email application", body: "Here is the rental application!", :attachments => {"rentalapp.pdf" => File.read(Rails.root.to_s + "/public/rentalapp.pdf")} )
		redirect_to properties_apply_path
	end

   def apply
		
   end

   def edit
   	@property = Property.find(params[:id])
   end

   def destroy
	    Property.find(params[:id]).destroy
	    redirect_to properties_all_path
	end

	def update
	    @property = Property.find(params[:id])
	       if @property.update_attributes(property_params)
              redirect_to properties_path
	       else
		       render 'edit'
		   end
	end

    private
	def property_params
	    params.require(:property).permit(:property_id, :address, :city, :state, :zip, :monthly_rent, :date_available, :bedrooms, :bathrooms, :square_feet, :description, :pet_policy, :security_deposit, :application_fee, :avatar)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end

  def new
  	
  end

  def create
  	puts "These are my params: #{params.inspect}"
  	@tennant = Tennant.where(email: params[:email], password: params[:password]).first
  	puts "did we get a user"
  	if @tennant
  		session[:tennant_id] = @tennant.id
  		redirect_to @tennant
  	else 
  		render "new"
  	end
  end

  def destroy
  	session[:tennant_id] = nil
  	redirect_to root_path 
  end
end

app/controllers/tennants_controller.rb
class TennantsController < ApplicationController
  def index
  	@tennants = Tennant.all
  end

  def new
  	@tennant = Tennant.new
  	@property_id = params[:tennant][:property_id]
  end

  def create
  	@tennant = Tennant.new(tennant_params)
      if @tennant.save
        session[:tennant_id] = @tennant.id 
        redirect_to root_path
      else
        render 'new'
    end
  end

  def edit
    @tennant = Tennant.find(params[:id])
  end

  def update
    @tennant = Tennant.find(params[:id]).update_attributes(tennant_params)
    redirect_to tennant_path
  end

  def destroy
  	Tennant.find(params[:id]).destroy
 	  redirect_to tennants_path
  end

  def maintanence
    @tennant = Tennant.find(session[:tennant_id])
  end
  # pony gem used for a tennant to send an email to the landlord to request maintanence
  def maintanence_request
    @tennant = Tennant.find(session[:tennant_id])
  	Pony.mail(from: @tennant.email, to: "bradwflint@gmail.com", subject: "Maintanence request", body: "#{@tennant.first_name} says:\n#{params[:message]}" )
    redirect_to tennants_maintanence_path
  end

  def pay
  	@tennant = Tennant.find(params[:id])
  end

  def show
    @tennant = Tennant.find(session[:tennant_id])
  end

  private
  def tennant_params
    params.require(:tennant).permit(:first_name, :last_name, :email, :password, :property_id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tennants_helper.rb
module TennantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evolution</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	<!-- gets the signed in tennant params -->
  <% current_tennant = Tennant.find(session[:tennant_id]) if session[:tennant_id] %>
  <body>
  	<header>
  	<!-- links to the pages throughout the site -->
	  <div class="home_btns">
	      	<!-- buttons displayed if the landlord is signed in -->
	          <% if landlord_signed_in? %>
		          <%= link_to "Homes For Rent", properties_path, :class => "btn" %> |
		          <%= link_to "All Properties", properties_all_path, :class => "btn" %> |
		          <%= link_to "Create New Property", new_property_path, :class => "btn" %> |
		          <%= link_to "Tennants", tennants_path, :class => "btn" %> |
		          <%= link_to "Sign Out", destroy_landlord_session_path, method: :delete, :class => "btn" %> 
		         <!-- buttons displayed if the tennant is signed in -->
	          <% elsif session[:tennant_id] %>
		          <%= link_to "Edit Account", edit_tennant_path(current_tennant), :class => "btn"  %> |
		          <%= link_to "Homes For Rent", properties_path, :class => "btn" %> |
		          <%= link_to "Request Maintanence", tennants_maintanence_path, :class => "btn" %> |
				  <%= link_to "Pay Rent", tennants_pay_path(current_tennant), :class => "btn" %> |
				  <%= link_to "Sign Out", sign_out_path, method: :delete, :class => "btn" %>
				  <!-- buttons displayed if neither landlord or tennant signed in -->
	          <% else %>  
		          <%= link_to "Home", root_path, :class => 'btn' %> |
		          <%= link_to "Homes for Rent", properties_path, :class => "btn" %> |
		          <%= link_to "Apply", properties_apply_path, :class => "btn" %> |
		          <%= link_to "Contact Us", landlords_contact_path, :class => "btn" %> |
			      <%= link_to "Landlord Login", landlord_session_path, :class => "btn" %> |
			      <%= link_to "Tennant Login", sessions_path, :class => "btn" %>
			  
		      <% end %>  
	      
	  </div>

	   <div class="logo">
			<%=image_tag("logo.jpg")%>
	   </div>

	   <div id= "phone">
	   		<h1>(801) 772-4444</h1>
	   </div>

	</header>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <div class="footer">
		<p>&copy 2017 Evolution Property Management Inc &nbsp; &nbsp;2281 West Temple, Suite 300 
		Salt Lake City, Utah 84121</p>
	</div>
</html>